[tool.poetry]
name = "{{cookiecutter.repo_name}}"
version = "0.1.0"
description = ""
authors = ["Christoph Clement <christoph.clement@artorg.unibe.ch>"]

[tool.poetry.dependencies]
python = "^3.8"
click = "^7.1.1"
tqdm = "^4.45.0"
loguru = "^0.5.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2"
pre-commit = "^2.2.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.masonry.api"
