[tool.poetry]
name = "{{cookiecutter.repo_name}}"
version = "0.1.0"
description = ""
authors = ["Christoph Clement <christoph.clement@tum.de>"]

[tool.poetry.dependencies]
python = "^3.8"
click = "^7.1.1"
tqdm = "^4.45.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pre-commit = "^2.2.0"

[tool.poetry.scripts]
{{cookiecutter.script_name}} = "{{cookiecutter.package_name}}.{{cookiecutter.script_name}}:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
